/**
 * IPC Channel definitions
 * Main-Renderer 간 통신 채널 정의
 */
export const CHANNELS = {
  // App
  GET_APP_VERSION: 'GET_APP_VERSION',
  GET_SYSTEM_INFO: 'GET_SYSTEM_INFO',

  // Package
  PACKAGE_LIST: 'PACKAGE_LIST',
  PACKAGE_GET: 'PACKAGE_GET',
  PACKAGE_CREATE: 'PACKAGE_CREATE',
  PACKAGE_UPDATE: 'PACKAGE_UPDATE',
  PACKAGE_DELETE: 'PACKAGE_DELETE',
  PACKAGE_LINK_RESOURCE: 'PACKAGE_LINK_RESOURCE',
  PACKAGE_UNLINK_RESOURCE: 'PACKAGE_UNLINK_RESOURCE',
  PACKAGE_GET_RESOURCES: 'PACKAGE_GET_RESOURCES',

  // Connection
  CONNECTION_LIST: 'CONNECTION_LIST',
  CONNECTION_GET: 'CONNECTION_GET',
  CONNECTION_CREATE: 'CONNECTION_CREATE',
  CONNECTION_UPDATE: 'CONNECTION_UPDATE',
  CONNECTION_DELETE: 'CONNECTION_DELETE',
  CONNECTION_TEST: 'CONNECTION_TEST',

  // Diagram
  DIAGRAM_LIST: 'DIAGRAM_LIST',
  DIAGRAM_GET: 'DIAGRAM_GET',
  DIAGRAM_CREATE: 'DIAGRAM_CREATE',
  DIAGRAM_UPDATE: 'DIAGRAM_UPDATE',
  DIAGRAM_DELETE: 'DIAGRAM_DELETE',
  DIAGRAM_UPDATE_META: 'DIAGRAM_UPDATE_META',
  DIAGRAM_GET_LAYOUT: 'DIAGRAM_GET_LAYOUT',
  DIAGRAM_SAVE_LAYOUT: 'DIAGRAM_SAVE_LAYOUT',

  // Diagram Versions
  DIAGRAM_VERSION_LIST: 'DIAGRAM_VERSION_LIST',
  DIAGRAM_VERSION_CREATE: 'DIAGRAM_VERSION_CREATE',
  DIAGRAM_VERSION_RESTORE: 'DIAGRAM_VERSION_RESTORE',

  // Migration
  MIGRATION_LIST: 'MIGRATION_LIST',
  MIGRATION_CREATE: 'MIGRATION_CREATE',
  MIGRATION_APPLY: 'MIGRATION_APPLY',
  MIGRATION_DELETE: 'MIGRATION_DELETE',

  // View Snapshot
  VIEW_SNAPSHOT_LIST: 'VIEW_SNAPSHOT_LIST',
  VIEW_SNAPSHOT_CREATE: 'VIEW_SNAPSHOT_CREATE',
  VIEW_SNAPSHOT_RESTORE: 'VIEW_SNAPSHOT_RESTORE',
  VIEW_SNAPSHOT_DELETE: 'VIEW_SNAPSHOT_DELETE',

  // Schema (Real)
  SCHEMA_FETCH_REAL: 'SCHEMA_FETCH_REAL',

  // Diff
  SCHEMA_DIFF: 'SCHEMA_DIFF',
  SCHEMA_APPLY_REAL_TO_VIRTUAL: 'SCHEMA_APPLY_REAL_TO_VIRTUAL',

  // DDL
  DDL_PARSE: 'DDL_PARSE',
  DDL_GENERATE: 'DDL_GENERATE',

  // Query
  QUERY_EXECUTE: 'QUERY_EXECUTE',
  QUERY_LIST: 'QUERY_LIST',
  QUERY_SAVE: 'QUERY_SAVE',
  QUERY_UPDATE: 'QUERY_UPDATE',
  QUERY_DELETE: 'QUERY_DELETE',
  QUERY_HISTORY_LIST: 'QUERY_HISTORY_LIST',

  // Document
  DOCUMENT_LIST: 'DOCUMENT_LIST',
  DOCUMENT_GET: 'DOCUMENT_GET',
  DOCUMENT_CREATE: 'DOCUMENT_CREATE',
  DOCUMENT_UPDATE: 'DOCUMENT_UPDATE',
  DOCUMENT_DELETE: 'DOCUMENT_DELETE',
  DOCUMENT_AUTO_GENERATE: 'DOCUMENT_AUTO_GENERATE',
  DOCUMENT_EXPORT: 'DOCUMENT_EXPORT',

  // Validation
  VALIDATION_RUN: 'VALIDATION_RUN',

  // Mocking
  MOCK_GENERATE: 'MOCK_GENERATE',
  MOCK_EXPORT: 'MOCK_EXPORT',
} as const;

export type TChannelKeys = keyof typeof CHANNELS;
