import { documentRepository } from '#/repositories';
import { diagramRepository } from '#/repositories';
import type { IDocument, ITable, IColumn } from '~/shared/types/db';

function generateTableMarkdown(table: ITable): string {
  const lines: string[] = [];
  lines.push(`## ${table.name}`);
  if (table.comment) {
    lines.push(`\n${table.comment}`);
  }
  lines.push('');
  lines.push('| Column | Type | Nullable | Key | Default | Comment |');
  lines.push('|--------|------|----------|-----|---------|---------|');

  for (const col of table.columns) {
    const key = col.keyTypes?.join(',') ?? '';
    const nullable = col.nullable ? 'YES' : 'NO';
    const defaultVal = col.defaultValue ?? '';
    const comment = col.comment ?? '';
    lines.push(`| ${col.name} | ${col.dataType} | ${nullable} | ${key} | ${defaultVal} | ${comment} |`);
  }

  // Foreign key references
  const fkColumns = table.columns.filter(c => c.reference);
  if (fkColumns.length > 0) {
    lines.push('');
    lines.push('### Foreign Keys');
    for (const col of fkColumns) {
      const ref = col.reference!;
      lines.push(`- \`${col.name}\` -> \`${ref.table}.${ref.column}\``);
      if (ref.onDelete) lines.push(`  - ON DELETE ${ref.onDelete}`);
      if (ref.onUpdate) lines.push(`  - ON UPDATE ${ref.onUpdate}`);
    }
  }

  // Constraints
  if (table.constraints.length > 0) {
    lines.push('');
    lines.push('### Constraints');
    for (const c of table.constraints) {
      lines.push(`- \`${c.name}\` (${c.type}): ${c.columns.join(', ')}`);
    }
  }

  return lines.join('\n');
}

export const documentService = {
  list(): IDocument[] {
    return documentRepository.list();
  },

  getById(id: string): IDocument {
    const doc = documentRepository.getById(id);
    if (!doc) throw new Error(`Document not found: ${id}`);
    return doc;
  },

  create(data: { name: string; content: string; autoGenerated?: boolean }): IDocument {
    return documentRepository.create(data);
  },

  update(id: string, data: { name?: string; content?: string }): IDocument {
    const existing = documentRepository.getById(id);
    if (!existing) throw new Error(`Document not found: ${id}`);
    return documentRepository.update(id, data);
  },

  deleteById(id: string): void {
    documentRepository.deleteById(id);
  },

  autoGenerate(diagramId: string): IDocument {
    const diagram = diagramRepository.getById(diagramId);
    if (!diagram) throw new Error(`Diagram not found: ${diagramId}`);

    const lines: string[] = [];
    lines.push(`# Database Documentation: ${diagram.name}`);
    lines.push('');
    lines.push(`Generated at: ${new Date().toISOString()}`);
    lines.push('');
    lines.push(`Total tables: ${diagram.tables.length}`);
    lines.push('');

    // Table of contents
    lines.push('## Table of Contents');
    for (const table of diagram.tables) {
      lines.push(`- [${table.name}](#${table.name.toLowerCase().replace(/[^a-z0-9]/g, '-')})`);
    }
    lines.push('');

    // Table details
    for (const table of diagram.tables) {
      lines.push(generateTableMarkdown(table));
      lines.push('');
    }

    const content = lines.join('\n');
    const name = `${diagram.name} - Documentation`;

    return documentRepository.create({
      name,
      content,
      autoGenerated: true,
    });
  },
};
