import { describe, expect, it } from 'vitest';
import type { ITable } from '~/shared/types/db';
import { sanitizeImportedTables } from './sanitizeImportedTables';

function makeTable(overrides: Partial<ITable> = {}): ITable {
  return {
    id: '11111111-1111-1111-1111-111111111111',
    name: 'tbl_real',
    comment: '',
    columns: [
      {
        id: 'c1',
        name: 'id',
        dataType: 'int(11)',
        keyTypes: ['PK'],
        isAutoIncrement: true,
        defaultValue: null,
        nullable: false,
        comment: '',
        reference: null,
        constraints: [],
        ordinalPosition: 1,
      },
    ],
    constraints: [],
    ...overrides,
  };
}

describe('sanitizeImportedTables', () => {
  it('removes synthetic default new_table generated by canvas template', () => {
    const synthetic = makeTable({
      id: 'tbl-1730000000000-0',
      name: 'new_table',
      columns: [
        {
          id: 'col-1730000000000-0-0',
          name: 'id',
          dataType: 'BIGINT',
          keyTypes: ['PK'],
          isAutoIncrement: true,
          defaultValue: null,
          nullable: false,
          comment: 'Primary key',
          reference: null,
          constraints: [],
          ordinalPosition: 0,
        },
      ],
    });

    const kept = makeTable({ id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', name: 'tbl_member' });
    const sanitized = sanitizeImportedTables([synthetic, kept]);

    expect(sanitized).toHaveLength(1);
    expect(sanitized[0].name).toBe('tbl_member');
  });

  it('keeps normal tables including user-created table named new_table with non-synthetic id', () => {
    const realNewTable = makeTable({
      id: '22222222-2222-2222-2222-222222222222',
      name: 'new_table',
      columns: [
        {
          id: 'c2',
          name: 'id',
          dataType: 'BIGINT',
          keyTypes: ['PK'],
          isAutoIncrement: true,
          defaultValue: null,
          nullable: false,
          comment: '',
          reference: null,
          constraints: [],
          ordinalPosition: 1,
        },
      ],
    });

    const sanitized = sanitizeImportedTables([realNewTable]);
    expect(sanitized).toHaveLength(1);
    expect(sanitized[0].id).toBe(realNewTable.id);
  });
});
