import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { documentApi } from '../api/documentApi';
import type { TExportFormat } from '@/entities/document';

const documentKeys = {
  all: ['documents'] as const,
  lists: () => [...documentKeys.all, 'list'] as const,
  detail: (id: string) => [...documentKeys.all, 'detail', id] as const,
};

export function useDocuments() {
  return useQuery({
    queryKey: documentKeys.lists(),
    queryFn: async () => {
      const result = await documentApi.list();
      if (!result.success) throw new Error('Failed to fetch documents');
      return result.data;
    },
  });
}

export function useDocument(id: string) {
  return useQuery({
    queryKey: documentKeys.detail(id),
    queryFn: async () => {
      const result = await documentApi.get(id);
      if (!result.success) throw new Error('Failed to fetch document');
      return result.data;
    },
    enabled: !!id,
  });
}

export function useCreateDocument() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (args: { name: string; content: string }) => documentApi.create(args),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: documentKeys.lists() });
    },
  });
}

export function useUpdateDocument() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (args: { id: string; name?: string; content?: string }) =>
      documentApi.update(args),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: documentKeys.lists() });
      queryClient.invalidateQueries({ queryKey: documentKeys.detail(variables.id) });
    },
  });
}

export function useDeleteDocument() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: string) => documentApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: documentKeys.lists() });
    },
  });
}

export function useAutoGenerateDocument() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (diagramId: string) => documentApi.autoGenerate(diagramId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: documentKeys.lists() });
    },
  });
}

export function useExportDocument() {
  return useMutation({
    mutationFn: (args: { documentId: string; format: TExportFormat; outputPath?: string }) =>
      documentApi.export(args),
  });
}
