import { describe, expect, it } from 'vitest'
import type { Column, TableDef } from './types'
import { generateDdl } from './ddl'

const col = (id: string, name: string, type: string, extra: Partial<Column> = {}): Column => ({
  id,
  name,
  type,
  nullable: false,
  defaultValue: null,
  comment: '',
  ...extra
})

const orders: TableDef = {
  id: 't',
  designId: 'd',
  name: 'orders',
  comment: '주문',
  columns: [
    col('c1', 'id', 'BIGINT UNSIGNED', { defaultValue: 'AUTO_INCREMENT', comment: 'PK' }),
    col('c2', 'status', "ENUM('a','b')", { defaultValue: "'a'" }),
    col('c3', 'payload', 'JSON', { nullable: true }),
    col('c4', 'created_at', 'DATETIME', { defaultValue: 'CURRENT_TIMESTAMP' })
  ],
  constraints: [{ id: 'k1', kind: 'pk', name: 'pk_orders', columns: [{ columnId: 'c1' }] }]
}

describe('generateDdl — 방언별 매핑', () => {
  it('mysql: 백틱 · AUTO_INCREMENT · InnoDB · 인라인 ENUM', () => {
    const ddl = generateDdl(orders, 'mysql')
    expect(ddl).toContain('`orders`')
    expect(ddl).toContain('AUTO_INCREMENT')
    expect(ddl).toContain('ENGINE=InnoDB')
    expect(ddl).toContain("ENUM('a','b')")
  })

  it('postgresql: 큰따옴표 · IDENTITY · UNSIGNED 소거 · DATETIME→TIMESTAMP · JSON→JSONB · ENUM 타입', () => {
    const ddl = generateDdl(orders, 'postgresql')
    expect(ddl).toContain('"orders"')
    expect(ddl).toContain('GENERATED BY DEFAULT AS IDENTITY')
    expect(ddl).not.toMatch(/UNSIGNED/)
    expect(ddl).not.toMatch(/DATETIME/)
    expect(ddl).toContain('TIMESTAMP')
    expect(ddl).toContain('JSONB')
    expect(ddl).toContain('CREATE TYPE')
  })

  it('sqlite: 단일 PK+자동증가 → INTEGER PRIMARY KEY AUTOINCREMENT · JSON→TEXT · ENUM→CHECK', () => {
    const ddl = generateDdl(orders, 'sqlite')
    expect(ddl).toContain('INTEGER PRIMARY KEY AUTOINCREMENT')
    expect(ddl).not.toContain('AUTO_INCREMENT')
    expect(ddl).toContain('CHECK')
    expect(ddl).toMatch(/payload"?\s+TEXT/i)
  })
})
