import { describe, expect, it } from 'vitest'
import type { Column, TableDef } from './types'
import { generateDdl, quoteId } from './ddl'

const col = (id: string, name: string, type: string, extra: Partial<Column> = {}): Column => ({
  id,
  name,
  type,
  nullable: false,
  defaultValue: null,
  comment: '',
  ...extra
})

const orders: TableDef = {
  id: 't',
  designId: 'd',
  name: 'orders',
  comment: '주문',
  columns: [
    col('c1', 'id', 'BIGINT UNSIGNED', { defaultValue: 'AUTO_INCREMENT', comment: 'PK' }),
    col('c2', 'status', "ENUM('a','b')", { defaultValue: "'a'" }),
    col('c3', 'payload', 'JSON', { nullable: true }),
    col('c4', 'created_at', 'DATETIME', { defaultValue: 'CURRENT_TIMESTAMP' })
  ],
  constraints: [{ id: 'k1', kind: 'pk', name: 'pk_orders', columns: [{ columnId: 'c1' }] }]
}

describe('generateDdl — 방언별 매핑', () => {
  it('mysql: 백틱 · AUTO_INCREMENT · InnoDB · 인라인 ENUM', () => {
    const ddl = generateDdl(orders, 'mysql')
    expect(ddl).toContain('`orders`')
    expect(ddl).toContain('AUTO_INCREMENT')
    expect(ddl).toContain('ENGINE=InnoDB')
    expect(ddl).toContain("ENUM('a','b')")
  })

  it('postgresql: 큰따옴표 · IDENTITY · UNSIGNED 소거 · DATETIME→TIMESTAMP · JSON→JSONB · ENUM 타입', () => {
    const ddl = generateDdl(orders, 'postgresql')
    expect(ddl).toContain('"orders"')
    expect(ddl).toContain('GENERATED BY DEFAULT AS IDENTITY')
    expect(ddl).not.toMatch(/UNSIGNED/)
    expect(ddl).not.toMatch(/DATETIME/)
    expect(ddl).toContain('TIMESTAMP')
    expect(ddl).toContain('JSONB')
    expect(ddl).toContain('CREATE TYPE')
  })

  it('sqlite: 단일 PK+자동증가 → INTEGER PRIMARY KEY AUTOINCREMENT · JSON→TEXT · ENUM→CHECK', () => {
    const ddl = generateDdl(orders, 'sqlite')
    expect(ddl).toContain('INTEGER PRIMARY KEY AUTOINCREMENT')
    expect(ddl).not.toContain('AUTO_INCREMENT')
    expect(ddl).toContain('CHECK')
    expect(ddl).toMatch(/payload"?\s+TEXT/i)
  })
})

// 화면 회귀(사용자 제보 2026-07-30): DDL 첫 줄에 `-- <테이블> (<방언>)` 머리 주석을 달았다.
// 테이블 이름은 바로 아래 CREATE 문에, 방언은 상단 컨텍스트 바에 이미 있다 — 자명한 것을
// 되풀이하는 설명이라 걷어냈다. 첫 줄은 언제나 실행되는 문장으로 시작한다.
describe('generateDdl — 자명한 것을 주석으로 되풀이하지 않는다', () => {
  const firstLine = (s: string) => s.split('\n')[0]

  it('테이블: 첫 줄이 머리 주석이 아니다', () => {
    for (const d of ['mysql', 'mariadb', 'postgresql', 'sqlite'] as const) {
      const ddl = generateDdl(orders, d)
      expect(firstLine(ddl).startsWith('--')).toBe(false)
      // 어느 줄에서도 이름을 주석으로 되풀이하지 않는다(머리를 아래로 옮기는 회귀 차단).
      expect(ddl).not.toMatch(/^--.*orders/m)
    }
  })

  it('뷰: 첫 줄이 머리 주석이 아니다', () => {
    for (const d of ['mysql', 'postgresql', 'sqlite'] as const) {
      expect(firstLine(generateDdl(activeProducts, d)).startsWith('--')).toBe(false)
    }
  })

  it('방언 이름(MySQL 8.0 등)을 DDL 본문에 박지 않는다', () => {
    expect(generateDdl(orders, 'mysql')).not.toMatch(/MySQL 8\.0/)
    expect(generateDdl(orders, 'postgresql')).not.toMatch(/PostgreSQL/)
  })
})

// 보안 회귀(감사 HIGH): MCP set_schema 가 식별자를 원격 작성자에게 열었다 —
// 이름에 인용부호가 섞이면 인용을 탈출해 실 DB DDL 로 주입될 수 있었다.
describe('quoteId — 식별자 인용부호 이스케이프(주입 차단)', () => {
  it('정상 식별자는 출력 불변', () => {
    expect(quoteId('mysql', 'orders')).toBe('`orders`')
    expect(quoteId('postgresql', 'orders')).toBe('"orders"')
  })

  it('mysql: 백틱을 이중화해 인용 탈출을 막는다', () => {
    // `id` INTEGER); DROP TABLE users;--  → 백틱이 이중화되어 한 식별자 안에 갇힌다
    const evil = 'id` INTEGER); DROP TABLE users;-- '
    const q = quoteId('mysql', evil)
    expect(q).toBe('`id`` INTEGER); DROP TABLE users;-- `')
    // 열고 닫는 백틱을 벗기면 내부에 홀수 개(미이중화) 백틱이 남지 않는다
    expect(q.slice(1, -1)).toBe('id`` INTEGER); DROP TABLE users;-- ')
  })

  it('postgresql/sqlite: 큰따옴표를 이중화한다', () => {
    expect(quoteId('postgresql', 'a" ; DROP TABLE t; --')).toBe('"a"" ; DROP TABLE t; --"')
    expect(quoteId('sqlite', 'x"y')).toBe('"x""y"')
  })

  it('조작 식별자로 만든 DDL 에 주입 구문이 살아있는 백틱으로 남지 않는다', () => {
    const t: TableDef = {
      id: 't', designId: 'd', name: 'orders', comment: '',
      columns: [col('c1', 'id` ); DROP TABLE users; -- ', 'INT')],
      constraints: []
    }
    const ddl = generateDdl(t, 'mysql')
    // 컬럼 정의 줄: 조작 이름이 하나의 이중화된 식별자로만 나타난다
    expect(ddl).toContain('`id`` ); DROP TABLE users; -- `')
  })
})

// ── 뷰 DDL — 설계부에서 선언한 뷰(isView + viewSql)는 CREATE TABLE 이 아니라 CREATE VIEW 로 나온다 ──
const activeProducts: TableDef = {
  id: 'v',
  designId: 'd',
  name: 'v_active_products',
  comment: '판매 중 상품',
  columns: [col('vc1', 'id', 'BIGINT UNSIGNED'), col('vc2', 'name', 'VARCHAR(200)')],
  constraints: [],
  isView: true,
  viewSql: 'SELECT id, name FROM products WHERE deleted_at IS NULL'
}

describe('generateDdl — 뷰', () => {
  it('mysql: CREATE OR REPLACE VIEW + 본문 SELECT', () => {
    const ddl = generateDdl(activeProducts, 'mysql')
    expect(ddl).toContain('CREATE OR REPLACE VIEW `v_active_products` AS')
    expect(ddl).toContain('SELECT id, name FROM products WHERE deleted_at IS NULL;')
    expect(ddl).not.toContain('CREATE TABLE')
  })

  it('sqlite: OR REPLACE 를 지원하지 않으므로 CREATE VIEW 로만 낸다', () => {
    const ddl = generateDdl(activeProducts, 'sqlite')
    expect(ddl).toContain('CREATE VIEW "v_active_products" AS')
    expect(ddl).not.toContain('OR REPLACE')
  })

  it('postgresql: 설명은 COMMENT ON VIEW 로 따로 붙는다', () => {
    const ddl = generateDdl(activeProducts, 'postgresql')
    expect(ddl).toContain('CREATE OR REPLACE VIEW "v_active_products" AS')
    expect(ddl).toContain(`COMMENT ON VIEW "v_active_products" IS '판매 중 상품';`)
  })

  it('본문 끝의 세미콜론이 겹치지 않는다', () => {
    const ddl = generateDdl({ ...activeProducts, viewSql: 'SELECT 1;' }, 'mysql')
    expect(ddl).not.toContain(';;')
  })

  it('본문이 비면 무엇이 비었는지 알리고 DDL 은 깨지지 않는다', () => {
    const ddl = generateDdl({ ...activeProducts, viewSql: '' }, 'mysql')
    expect(ddl).toContain('뷰 본문(SELECT)이 비어 있어요')
    // 운영부(역설계)로 들어온 뷰도 본문이 비는데, 그건 Definition 에서 채울 대상이 아니다 — 둘 다 알린다.
    expect(ddl).toContain('실 DB 역설계는 본문을 가져오지 않습니다')
    expect(ddl).toContain('CREATE OR REPLACE VIEW `v_active_products` AS')
  })

  it('역설계로 들어온 뷰(본문 없음)도 CREATE TABLE 로 잘못 나오지 않는다', () => {
    const introspected: TableDef = { ...activeProducts, viewSql: undefined }
    const ddl = generateDdl(introspected, 'mysql')
    expect(ddl).toContain('CREATE OR REPLACE VIEW')
    expect(ddl).not.toContain('CREATE TABLE')
  })

  it('뷰 이름도 식별자 인용을 탈출하지 못한다(주입 방어)', () => {
    const ddl = generateDdl({ ...activeProducts, name: 'v`; DROP TABLE users; --' }, 'mysql')
    expect(ddl).toContain('`v``; DROP TABLE users; --`')
  })
})
