import type { ReactNode } from 'react'
import { AlignLeft, Copy } from 'lucide-react'
import { Button } from '@renderer/ui/button'
import { useActiveDesign } from '../../designs/store'
import { useActiveTable } from './store'
import { generateDdl } from './ddl'

// 방언 전반의 토큰: "id" / `id` / 'str' / 키워드 / 타입 / 숫자
const SQL_TOKEN =
  /("(?:[^"]|"")*")|(`[^`]*`)|('(?:[^']|'')*')|\b(GENERATED BY DEFAULT AS IDENTITY|COMMENT ON TABLE|COMMENT ON COLUMN|CREATE TABLE|CREATE TYPE|CREATE INDEX|PRIMARY KEY|FOREIGN KEY|UNIQUE KEY|DEFAULT CHARSET|ON DELETE|ON UPDATE|AS ENUM|NOT NULL|CONSTRAINT|REFERENCES|AUTO_INCREMENT|AUTOINCREMENT|CURRENT_TIMESTAMP|RESTRICT|CASCADE|UNIQUE|INDEX|ENGINE|DEFAULT|CHECK|IDENTITY|GENERATED|COMMENT|NULL|DESC|AS|ON|IS|IN)\b|\b(BIGSERIAL|SERIAL|INTEGER|BIGINT|UNSIGNED|VARCHAR|ENUM|DECIMAL|NUMERIC|CHAR|JSONB|JSON|TEXT|DATETIME|TIMESTAMP|BOOLEAN|INT)\b|\b\d+(?:\.\d+)?\b/g

/** 한 줄 구문 강조 — id=fg, string=success, keyword=accent, type=accent-2, number=info. */
function highlight(line: string): ReactNode {
  if (/^\s*--/.test(line)) return <span className="italic text-muted">{line}</span>
  const nodes: ReactNode[] = []
  let last = 0
  let key = 0
  let m: RegExpExecArray | null
  SQL_TOKEN.lastIndex = 0
  while ((m = SQL_TOKEN.exec(line)) !== null) {
    if (m.index > last) nodes.push(line.slice(last, m.index))
    const cls =
      m[1] || m[2]
        ? 'text-fg'
        : m[3]
          ? 'text-success'
          : m[4]
            ? 'font-semibold text-accent'
            : m[5]
              ? 'text-accent-2'
              : 'text-info'
    nodes.push(
      <span key={key++} className={cls}>
        {m[0]}
      </span>
    )
    last = m.index + m[0].length
  }
  if (last < line.length) nodes.push(line.slice(last))
  return nodes
}

export function SqlForm() {
  const table = useActiveTable()
  const design = useActiveDesign()

  // 부모(DefinitionWorkspace)가 설계 선택·테이블 존재를 보장하지만 방어적으로 가드.
  if (!table || !design) return null

  // DDL 은 설계의 방언 그대로 — 방언은 선택지가 아니라 설계의 고정 속성.
  const lines = generateDdl(table, design.dialect).split('\n')

  return (
    <div className="mx-auto max-w-[1160px] p-5">
      <div className="overflow-hidden rounded-[10px] border border-line">
        <div className="flex h-9 items-center gap-2.5 border-b border-line bg-panel px-3">
          <span className="font-mono text-[12px] text-fg">{table.name}.sql</span>
          <span className="flex items-center gap-1.5 text-[11px] text-success">
            <span className="size-1.5 rounded-full bg-success" />
            Table 폼과 동기화됨
          </span>
          <div className="ml-auto flex gap-1.5">
            <Button variant="secondary" size="sm">
              <AlignLeft />
              Format
            </Button>
            <Button variant="secondary" size="sm">
              <Copy />
              Copy
            </Button>
          </div>
        </div>

        <div className="flex bg-canvas">
          <div className="shrink-0 select-none border-r border-line bg-panel py-3.5 text-right font-mono text-[12px] leading-[1.75] tabular-nums text-muted/70">
            {lines.map((_, i) => (
              <div key={i} className="pl-3.5 pr-2.5">
                {i + 1}
              </div>
            ))}
          </div>
          <pre className="selectable flex-1 overflow-x-auto px-4 py-3.5 font-mono text-[12px] leading-[1.75] text-fg">
            {lines.map((l, i) => (
              <div key={i}>{l ? highlight(l) : ' '}</div>
            ))}
          </pre>
        </div>
      </div>
    </div>
  )
}
