import { describe, expect, it } from 'vitest'
import { tokenizeSqlLine } from './sqlHighlight'

/** 토큰을 이어붙이면 원문과 정확히 같아야 한다(무손실 분해). */
const joined = (line: string): string =>
  tokenizeSqlLine(line)
    .map((t) => t.text)
    .join('')

describe('tokenizeSqlLine', () => {
  it('주석 줄은 통째로 muted 한 토큰', () => {
    const tokens = tokenizeSqlLine('  -- users  (MySQL)')
    expect(tokens).toEqual([{ text: '  -- users  (MySQL)', className: 'italic text-muted' }])
  })

  it('키워드는 accent 로 강조', () => {
    const kw = tokenizeSqlLine('CREATE TABLE `users` (').find((t) => t.text === 'CREATE TABLE')
    expect(kw?.className).toBe('font-semibold text-accent')
  })

  it('백틱/큰따옴표 식별자는 fg', () => {
    expect(tokenizeSqlLine('  `id` BIGINT').find((t) => t.text === '`id`')?.className).toBe(
      'text-fg'
    )
    expect(tokenizeSqlLine('  "id" BIGINT').find((t) => t.text === '"id"')?.className).toBe(
      'text-fg'
    )
  })

  it('작은따옴표 문자열은 success', () => {
    expect(
      tokenizeSqlLine("DEFAULT '값'").find((t) => t.text === "'값'")?.className
    ).toBe('text-success')
  })

  it('타입은 accent-2, 숫자는 info', () => {
    const tokens = tokenizeSqlLine('  `n` VARCHAR(255)')
    expect(tokens.find((t) => t.text === 'VARCHAR')?.className).toBe('text-accent-2')
    expect(tokens.find((t) => t.text === '255')?.className).toBe('text-info')
  })

  it('매칭 안 된 구간은 className 빈 gap 으로 보존 — 이어붙이면 원문', () => {
    const line = '  CONSTRAINT `pk_users` PRIMARY KEY (`id`)'
    expect(joined(line)).toBe(line)
    // gap(빈 className)이 최소 하나는 있다(괄호·공백 등).
    expect(tokenizeSqlLine(line).some((t) => t.className === '')).toBe(true)
  })

  it('빈 줄은 빈 토큰 배열', () => {
    expect(tokenizeSqlLine('')).toEqual([])
  })

  it('여러 줄 DDL 각 줄이 무손실 분해된다', () => {
    const ddl = [
      '-- users  (PostgreSQL)',
      'CREATE TABLE "users" (',
      '  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,',
      '  CONSTRAINT "pk_users" PRIMARY KEY ("id")',
      ');'
    ]
    for (const line of ddl) expect(joined(line)).toBe(line)
  })
})
