/**
 * DDL 한 줄 → 구문 강조 토큰(순수 함수 → 테스트 의무).
 * Studio SqlForm 과 Console › Definition SQL 뷰가 공유한다(하이라이터 단일 소스).
 * className 은 앱 시맨틱 토큰: id=fg · string=success · keyword=accent · type=accent-2 · number=info.
 */

// 방언 전반의 토큰: "id" / `id` / 'str' / 키워드 / 타입 / 숫자
const SQL_TOKEN =
  /("(?:[^"]|"")*")|(`[^`]*`)|('(?:[^']|'')*')|\b(GENERATED BY DEFAULT AS IDENTITY|COMMENT ON TABLE|COMMENT ON COLUMN|CREATE TABLE|CREATE TYPE|CREATE INDEX|PRIMARY KEY|FOREIGN KEY|UNIQUE KEY|DEFAULT CHARSET|ON DELETE|ON UPDATE|AS ENUM|NOT NULL|CONSTRAINT|REFERENCES|AUTO_INCREMENT|AUTOINCREMENT|CURRENT_TIMESTAMP|RESTRICT|CASCADE|UNIQUE|INDEX|ENGINE|DEFAULT|CHECK|IDENTITY|GENERATED|COMMENT|NULL|DESC|AS|ON|IS|IN)\b|\b(BIGSERIAL|SERIAL|INTEGER|BIGINT|UNSIGNED|VARCHAR|ENUM|DECIMAL|NUMERIC|CHAR|JSONB|JSON|TEXT|DATETIME|TIMESTAMP|BOOLEAN|INT)\b|\b\d+(?:\.\d+)?\b/g

export interface SqlToken {
  text: string
  /** 빈 문자열이면 강조 없는 일반 텍스트(gap). */
  className: string
}

/**
 * 한 줄을 강조 토큰 배열로 쪼갠다 — 매칭 안 된 사이 구간도 className:'' 토큰으로 보존해
 * 이어붙이면 원문과 정확히 일치한다. `-- 주석` 줄은 통째로 muted 처리.
 */
export function tokenizeSqlLine(line: string): SqlToken[] {
  if (/^\s*--/.test(line)) return [{ text: line, className: 'italic text-muted' }]
  const tokens: SqlToken[] = []
  let last = 0
  let m: RegExpExecArray | null
  SQL_TOKEN.lastIndex = 0
  while ((m = SQL_TOKEN.exec(line)) !== null) {
    if (m.index > last) tokens.push({ text: line.slice(last, m.index), className: '' })
    const className =
      m[1] || m[2]
        ? 'text-fg'
        : m[3]
          ? 'text-success'
          : m[4]
            ? 'font-semibold text-accent'
            : m[5]
              ? 'text-accent-2'
              : 'text-info'
    tokens.push({ text: m[0], className })
    last = m.index + m[0].length
  }
  if (last < line.length) tokens.push({ text: line.slice(last), className: '' })
  return tokens
}
