import { useState } from 'react';
import { FileText, Plus } from 'lucide-react';
import { Button } from '@/shared/components/ui/button';
import {
  DocumentEditor,
  DocumentPreview,
  AutoDocGenerator,
  ExportMenu,
  useDocuments,
  useCreateDocument,
  useUpdateDocument,
} from '@/features/db-documenting';

export function DbDocumentingPage() {
  const { data: documents } = useDocuments();
  const createDocument = useCreateDocument();
  const updateDocument = useUpdateDocument();
  const [selectedDocId, setSelectedDocId] = useState<string | null>(null);
  const [name, setName] = useState('');
  const [content, setContent] = useState('');

  function handleSelectDoc(docId: string) {
    const doc = documents?.find((d) => d.id === docId);
    if (doc) {
      setSelectedDocId(doc.id);
      setName(doc.name);
      setContent(doc.content);
    }
  }

  function handleNew() {
    setSelectedDocId(null);
    setName('');
    setContent('');
  }

  function handleSave() {
    if (!name.trim()) return;
    if (selectedDocId) {
      updateDocument.mutate({ id: selectedDocId, name, content });
    } else {
      createDocument.mutate(
        { name, content },
        {
          onSuccess: (result) => {
            if (result.success) setSelectedDocId(result.data.id);
          },
        },
      );
    }
  }

  function handleAutoGenerated(generatedContent: string) {
    setContent(generatedContent);
  }

  return (
    <div className="flex h-full flex-col">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border px-4 py-2">
        <div className="flex items-center gap-2">
          <FileText className="size-5" />
          <h1 className="text-xl font-semibold">Documenting</h1>
        </div>
        <div className="flex items-center gap-2">
          <AutoDocGenerator onGenerated={handleAutoGenerated} />
          <Button variant="outline" size="sm" onClick={handleNew}>
            <Plus className="size-4" />
            New
          </Button>
          <Button
            size="sm"
            onClick={handleSave}
            disabled={!name.trim() || createDocument.isPending || updateDocument.isPending}
          >
            {createDocument.isPending || updateDocument.isPending ? 'Saving...' : 'Save'}
          </Button>
          {selectedDocId && <ExportMenu documentId={selectedDocId} />}
        </div>
      </div>

      {/* Document list + split view */}
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar: Document list */}
        <div className="w-48 shrink-0 overflow-y-auto border-r border-border">
          <ul className="space-y-0.5 p-1">
            {documents?.map((doc) => (
              <li key={doc.id}>
                <button
                  type="button"
                  className={`w-full rounded px-2 py-1.5 text-left text-xs transition-colors hover:bg-muted ${
                    selectedDocId === doc.id ? 'bg-muted font-medium' : ''
                  }`}
                  onClick={() => handleSelectDoc(doc.id)}
                >
                  {doc.name}
                </button>
              </li>
            ))}
          </ul>
        </div>

        {/* Editor */}
        <div className="flex-1 border-r border-border">
          <DocumentEditor
            name={name}
            content={content}
            onNameChange={setName}
            onContentChange={setContent}
          />
        </div>

        {/* Preview */}
        <div className="flex-1">
          <DocumentPreview content={content} />
        </div>
      </div>
    </div>
  );
}
