import { describe, expect, it } from 'vitest'
import type { TableDef } from '../definition/types'
import {
  canBeMatchKey,
  createSeedSet,
  isDbGenerated,
  matchKeyBlockedReason,
  seedApplyReadiness,
  cycleSeedColumnRole,
  naturalKeyBacking,
  defaultNaturalKey,
  isAutoIncrement,
  pkColumnNames,
  seedColumnRole,
  seedSetCandidates,
  seedSetStatus,
  setSeedColumnRole,
  visibleSeedColumns
} from './seedSet'
import type { SeedSet } from './types'

/** CASE-studio-001~004 (docs/qa/db-studio.md) */

const col = (id: string, name: string, over: Partial<TableDef['columns'][number]> = {}) => ({
  id,
  name,
  type: 'VARCHAR(64)',
  nullable: false,
  defaultValue: null,
  comment: '',
  ...over
})

const table = (name: string, cols: TableDef['columns'], pk: string[] = [], over: Partial<TableDef> = {}): TableDef => ({
  id: `t:${name}`,
  designId: 'd1',
  name,
  comment: '',
  columns: cols,
  constraints: pk.length
    ? [{ id: `k:${name}.pk`, kind: 'pk', name: 'PRIMARY', columns: pk.map((c) => ({ columnId: c })) }]
    : [],
  ...over
})

describe('CASE-studio-001 자연키 기본값', () => {
  it('PK 컬럼들을 선언 순서대로 준다', () => {
    const t = table('roles', [col('c1', 'code'), col('c2', 'name')], ['c1'])
    expect(defaultNaturalKey(t)).toEqual(['code'])
  })

  it('복합 PK 는 전부 준다(순서 유지)', () => {
    const t = table('user_roles', [col('c1', 'user_id'), col('c2', 'role_code')], ['c2', 'c1'])
    expect(defaultNaturalKey(t)).toEqual(['role_code', 'user_id'])
  })

  it('PK 가 없으면 빈 배열', () => {
    expect(defaultNaturalKey(table('logs', [col('c1', 'msg')]))).toEqual([])
  })

  it('자동증가 PK 면 비운다 — 환경마다 값이 달라 짝짓기 기준이 못 된다', () => {
    const mysql = table('roles', [col('c1', 'id', { type: 'BIGINT', defaultValue: 'AUTO_INCREMENT' })], ['c1'])
    const pg = table('roles', [col('c1', 'id', { type: 'serial' })], ['c1'])
    const pgIdentity = table('roles', [col('c1', 'id', { type: 'BIGINT', defaultValue: 'GENERATED BY DEFAULT AS IDENTITY' })], ['c1'])
    const sqlite = table('roles', [col('c1', 'id', { type: 'INTEGER', defaultValue: 'AUTOINCREMENT' })], ['c1'])
    for (const t of [mysql, pg, pgIdentity, sqlite]) expect(defaultNaturalKey(t)).toEqual([])
  })

  it('DB 가 값을 만드는 PK(DEFAULT (UUID())·gen_random_uuid())도 비운다 — 회귀', () => {
    const mysqlUuid = table('roles', [col('c1', 'id', { type: 'CHAR(36)', defaultValue: '(UUID())' })], ['c1'])
    const pgUuid = table('roles', [col('c1', 'id', { defaultValue: 'gen_random_uuid()' })], ['c1'])
    for (const t of [mysqlUuid, pgUuid]) expect(defaultNaturalKey(t)).toEqual([])
  })

  it('복합 PK 중 하나만 자동증가여도 비운다', () => {
    const t = table(
      'x',
      [col('c1', 'id', { defaultValue: 'AUTO_INCREMENT' }), col('c2', 'code')],
      ['c1', 'c2']
    )
    expect(defaultNaturalKey(t)).toEqual([])
  })

  it('자동증가 아닌 컬럼은 오판하지 않는다', () => {
    expect(isAutoIncrement(col('c', 'code'))).toBe(false)
    expect(isAutoIncrement(col('c', 'serial_number', { type: 'VARCHAR(32)' }))).toBe(false)
  })

  it('pkColumnNames 는 존재하지 않는 컬럼 참조를 버린다', () => {
    const t = table('roles', [col('c1', 'code')], ['c1', 'ghost'])
    expect(pkColumnNames(t)).toEqual(['code'])
  })
})

describe('CASE-studio-002 컬럼 역할(짝짓기/포함/무시) — 한 축 3상태', () => {
  const base: SeedSet = {
    designId: 'd1',
    tableName: 'roles',
    naturalKey: ['code'],
    ignoredColumns: ['created_at'],
    strength: 'ensure',
    rows: []
  }

  it('역할 판정 — 선언 목록에서 셋 중 하나로 읽힌다', () => {
    expect(seedColumnRole(base, 'code')).toBe('key')
    expect(seedColumnRole(base, 'created_at')).toBe('ignore')
    expect(seedColumnRole(base, 'org')).toBe('include')
  })

  it('순환 순서는 짝짓기 → 포함 → 무시 → 짝짓기', () => {
    let s = { ...base, naturalKey: ['code'], ignoredColumns: [] as string[] }
    expect(seedColumnRole(s, 'code')).toBe('key')
    s = cycleSeedColumnRole(s, 'code')
    expect(seedColumnRole(s, 'code')).toBe('include')
    s = cycleSeedColumnRole(s, 'code')
    expect(seedColumnRole(s, 'code')).toBe('ignore')
    s = cycleSeedColumnRole(s, 'code')
    expect(seedColumnRole(s, 'code')).toBe('key')
  })

  it('한 컬럼이 짝짓기와 무시에 동시에 들어가지 않는다(상호 배타)', () => {
    const s = setSeedColumnRole(base, 'created_at', 'key')
    expect(s.naturalKey).toEqual(['code', 'created_at'])
    expect(s.ignoredColumns).toEqual([])

    const t = setSeedColumnRole(base, 'code', 'ignore')
    expect(t.ignoredColumns).toEqual(['created_at', 'code'])
    expect(t.naturalKey).toEqual([])
  })

  it('포함으로 바꾸면 양쪽 목록 어디에도 안 남는다', () => {
    const s = setSeedColumnRole(base, 'code', 'include')
    expect(s.naturalKey).toEqual([])
    expect(s.ignoredColumns).toEqual(['created_at'])
  })

  it('짝짓기로 켜는 순서가 키 구성 순서다', () => {
    const empty = { ...base, naturalKey: [] as string[] }
    const s = setSeedColumnRole(setSeedColumnRole(empty, 'org', 'key'), 'code', 'key')
    expect(s.naturalKey).toEqual(['org', 'code'])
  })

  it('다른 컬럼의 역할은 건드리지 않는다', () => {
    const s = cycleSeedColumnRole(base, 'org')
    expect(seedColumnRole(s, 'code')).toBe('key')
    expect(seedColumnRole(s, 'created_at')).toBe('ignore')
  })

  describe('무시 컬럼 감추기(보기 설정)', () => {
    const cols = [col('c1', 'code'), col('c2', 'org'), col('c3', 'created_at')]

    it('꺼져 있으면 컬럼을 그대로 준다(같은 배열)', () => {
      expect(visibleSeedColumns(base, cols, false)).toBe(cols)
    })

    it('켜면 무시 컬럼만 빠지고 나머지 순서는 그대로', () => {
      expect(visibleSeedColumns(base, cols, true).map((c) => c.name)).toEqual(['code', 'org'])
    })

    it('무시 컬럼이 없으면 켜도 아무것도 안 빠진다', () => {
      const s = { ...base, ignoredColumns: [] as string[] }
      expect(visibleSeedColumns(s, cols, true).map((c) => c.name)).toEqual(['code', 'org', 'created_at'])
    })

    it('선언(naturalKey·ignoredColumns)은 건드리지 않는다 — 보기 설정일 뿐', () => {
      visibleSeedColumns(base, cols, true)
      expect(base.ignoredColumns).toEqual(['created_at'])
      expect(base.naturalKey).toEqual(['code'])
    })

    it('전부 무시면 빈 목록', () => {
      const s = { ...base, naturalKey: [] as string[], ignoredColumns: ['code', 'org', 'created_at'] }
      expect(visibleSeedColumns(s, cols, true)).toEqual([])
    })
  })
})

describe('CASE-studio-003 세트 완전성', () => {
  it('자연키가 없으면 no-natural-key', () => {
    expect(seedSetStatus({ naturalKey: [] })).toBe('no-natural-key')
  })
  it('있으면 ok', () => {
    expect(seedSetStatus({ naturalKey: ['code'] })).toBe('ok')
  })
})

describe('CASE-studio-004 세트 등록 후보', () => {
  const roles = table('roles', [col('c1', 'code')], ['c1'])
  const perms = table('permissions', [col('c2', 'code')], ['c2'])
  const v = table('v_summary', [col('c3', 'x')], [], { isView: true })

  it('뷰와 이미 세트가 있는 테이블을 제외한다', () => {
    const got = seedSetCandidates([roles, perms, v], [{ tableName: 'roles' }])
    expect(got.map((t) => t.name)).toEqual(['permissions'])
  })

  it('후보가 없으면 빈 목록', () => {
    expect(seedSetCandidates([roles], [{ tableName: 'roles' }])).toEqual([])
  })

  it('세트가 없으면 뷰만 빠진다(원래 순서 유지)', () => {
    expect(seedSetCandidates([roles, v, perms], []).map((t) => t.name)).toEqual(['roles', 'permissions'])
  })
})

describe('createSeedSet', () => {
  it('설계 소속·기본 자연키·안전한 기본값(그대로 둠)으로 만든다', () => {
    const t = table('roles', [col('c1', 'code')], ['c1'])
    expect(createSeedSet(t)).toEqual({
      designId: 'd1',
      tableName: 'roles',
      naturalKey: ['code'],
      ignoredColumns: [],
      strength: 'ensure',
      rows: []
    })
  })
})

describe('CASE-studio-008 자연키를 UNIQUE 가 뒷받침하는가', () => {
  const uk = (id: string, name: string, cols: string[]): TableDef['constraints'][number] => ({
    id,
    kind: 'uk',
    name,
    columns: cols.map((c) => ({ columnId: c }))
  })

  it('PK 구성과 같으면 뒷받침됨', () => {
    const t = table('roles', [col('c1', 'code')], ['c1'])
    expect(naturalKeyBacking(t, ['code'])).toEqual({ backed: true, by: { kind: 'pk', name: 'PRIMARY' } })
  })

  it('UK 구성과 같으면 뒷받침됨 — 컬럼 순서는 상관없다', () => {
    const t = table('m', [col('c1', 'org'), col('c2', 'code')])
    t.constraints = [uk('k', 'uq_org_code', ['c2', 'c1'])]
    expect(naturalKeyBacking(t, ['org', 'code']).backed).toBe(true)
  })

  it('구성이 다르면 뒷받침 안 됨 — 부분집합도 인정하지 않는다(UPSERT 충돌 대상이 어긋난다)', () => {
    const t = table('m', [col('c1', 'org'), col('c2', 'code')])
    t.constraints = [uk('k', 'uq_org', ['c1'])]
    expect(naturalKeyBacking(t, ['org', 'code']).backed).toBe(false)
    expect(naturalKeyBacking(t, ['code']).backed).toBe(false)
  })

  it('제약이 아예 없으면 뒷받침 안 됨', () => {
    expect(naturalKeyBacking(table('m', [col('c1', 'code')]), ['code']).backed).toBe(false)
  })

  it('자연키 미선언이면 판정할 것이 없다', () => {
    expect(naturalKeyBacking(table('m', [col('c1', 'code')], ['c1']), [])).toEqual({ backed: false })
  })

  it('IDX(유일하지 않은 인덱스)는 뒷받침으로 치지 않는다', () => {
    const t = table('m', [col('c1', 'code')])
    t.constraints = [{ id: 'k', kind: 'idx', name: 'ix_code', columns: [{ columnId: 'c1' }] }]
    expect(naturalKeyBacking(t, ['code']).backed).toBe(false)
  })
})

describe('CASE-studio-065 짝짓기 기준 자격 · 반영 준비', () => {
  it('DB 가 값을 만드는 컬럼은 기준이 될 수 없다', () => {
    expect(canBeMatchKey(col('c', 'code'))).toBe(true)
    expect(canBeMatchKey(col('c', 'id', { defaultValue: 'AUTO_INCREMENT' }))).toBe(false)
    expect(canBeMatchKey(col('c', 'id', { type: 'serial' }))).toBe(false)
    expect(canBeMatchKey(col('c', 'id', { defaultValue: 'uuid()' }))).toBe(false)
    expect(canBeMatchKey(col('c', 'id', { defaultValue: 'gen_random_uuid()' }))).toBe(false)
    expect(canBeMatchKey(col('c', 'at', { defaultValue: 'CURRENT_TIMESTAMP' }))).toBe(false)
  })

  it('사람이 값을 주는 기본값은 DB 생성이 아니다', () => {
    expect(isDbGenerated(col('c', 'status', { defaultValue: "'pending'" }))).toBe(false)
    expect(isDbGenerated(col('c', 'n', { defaultValue: '0' }))).toBe(false)
  })

  it('못 고르는 이유를 문장으로 알려준다', () => {
    expect(matchKeyBlockedReason(col('c', 'code'))).toBeNull()
    expect(matchKeyBlockedReason(col('c', 'id', { defaultValue: 'AUTO_INCREMENT' }))).toContain('자동증가')
    expect(matchKeyBlockedReason(col('c', 'id', { defaultValue: 'uuid()' }))).toContain('DB 가 값을 만드는')
  })

  it('역할 순환에서 짝짓기를 건너뛴다(allowKey=false)', () => {
    let s: SeedSet = {
      designId: 'd1',
      tableName: 'roles',
      naturalKey: [],
      ignoredColumns: [],
      strength: 'ensure',
      rows: []
    }
    s = cycleSeedColumnRole(s, 'id', false) // include → ignore
    expect(s.ignoredColumns).toEqual(['id'])
    s = cycleSeedColumnRole(s, 'id', false) // ignore → include (짝짓기 건너뜀)
    expect(s.naturalKey).toEqual([])
    expect(s.ignoredColumns).toEqual([])
  })

  it('반영 준비: 기준에 안정적인 컬럼이 1개 이상 있어야 한다', () => {
    const t = table('roles', [col('c1', 'id', { defaultValue: 'AUTO_INCREMENT' }), col('c2', 'code')], ['c1'])
    const base = { tableName: 'roles' }
    expect(seedApplyReadiness({ ...base, naturalKey: ['code'] }, t)).toEqual({ ready: true })
    expect(seedApplyReadiness({ ...base, naturalKey: [] }, t)).toMatchObject({ ready: false, reason: 'no-key' })
    expect(seedApplyReadiness({ ...base, naturalKey: ['id'] }, t)).toMatchObject({
      ready: false,
      reason: 'volatile-key',
      columns: ['id']
    })
    expect(seedApplyReadiness({ ...base, naturalKey: ['code'] }, undefined)).toMatchObject({
      ready: false,
      reason: 'missing-table'
    })
  })
})
