import { describe, expect, it } from 'vitest'
import type { TableDef } from '../definition/types'
import {
  createSeedSet,
  defaultNaturalKey,
  isAutoIncrement,
  pkColumnNames,
  seedSetCandidates,
  seedSetStatus,
  toggleIgnoredColumn,
  toggleNaturalKeyColumn
} from './seedSet'
import type { SeedSet } from './types'

/** CASE-studio-001~004 (docs/qa/db-studio.md) */

const col = (id: string, name: string, over: Partial<TableDef['columns'][number]> = {}) => ({
  id,
  name,
  type: 'VARCHAR(64)',
  nullable: false,
  defaultValue: null,
  comment: '',
  ...over
})

const table = (name: string, cols: TableDef['columns'], pk: string[] = [], over: Partial<TableDef> = {}): TableDef => ({
  id: `t:${name}`,
  designId: 'd1',
  name,
  comment: '',
  columns: cols,
  constraints: pk.length
    ? [{ id: `k:${name}.pk`, kind: 'pk', name: 'PRIMARY', columns: pk.map((c) => ({ columnId: c })) }]
    : [],
  ...over
})

describe('CASE-studio-001 자연키 기본값', () => {
  it('PK 컬럼들을 선언 순서대로 준다', () => {
    const t = table('roles', [col('c1', 'code'), col('c2', 'name')], ['c1'])
    expect(defaultNaturalKey(t)).toEqual(['code'])
  })

  it('복합 PK 는 전부 준다(순서 유지)', () => {
    const t = table('user_roles', [col('c1', 'user_id'), col('c2', 'role_code')], ['c2', 'c1'])
    expect(defaultNaturalKey(t)).toEqual(['role_code', 'user_id'])
  })

  it('PK 가 없으면 빈 배열', () => {
    expect(defaultNaturalKey(table('logs', [col('c1', 'msg')]))).toEqual([])
  })

  it('자동증가 PK 면 비운다 — 환경마다 값이 달라 짝짓기 기준이 못 된다', () => {
    const mysql = table('roles', [col('c1', 'id', { type: 'BIGINT', defaultValue: 'AUTO_INCREMENT' })], ['c1'])
    const pg = table('roles', [col('c1', 'id', { type: 'serial' })], ['c1'])
    const pgIdentity = table('roles', [col('c1', 'id', { type: 'BIGINT', defaultValue: 'GENERATED BY DEFAULT AS IDENTITY' })], ['c1'])
    const sqlite = table('roles', [col('c1', 'id', { type: 'INTEGER', defaultValue: 'AUTOINCREMENT' })], ['c1'])
    for (const t of [mysql, pg, pgIdentity, sqlite]) expect(defaultNaturalKey(t)).toEqual([])
  })

  it('복합 PK 중 하나만 자동증가여도 비운다', () => {
    const t = table(
      'x',
      [col('c1', 'id', { defaultValue: 'AUTO_INCREMENT' }), col('c2', 'code')],
      ['c1', 'c2']
    )
    expect(defaultNaturalKey(t)).toEqual([])
  })

  it('자동증가 아닌 컬럼은 오판하지 않는다', () => {
    expect(isAutoIncrement(col('c', 'code'))).toBe(false)
    expect(isAutoIncrement(col('c', 'serial_number', { type: 'VARCHAR(32)' }))).toBe(false)
  })

  it('pkColumnNames 는 존재하지 않는 컬럼 참조를 버린다', () => {
    const t = table('roles', [col('c1', 'code')], ['c1', 'ghost'])
    expect(pkColumnNames(t)).toEqual(['code'])
  })
})

describe('CASE-studio-002 자연키·무시 컬럼 상호 배타', () => {
  const base: SeedSet = {
    designId: 'd1',
    tableName: 'roles',
    naturalKey: ['code'],
    ignoredColumns: ['created_at'],
    strength: 'ensure',
    rows: []
  }

  it('무시 컬럼을 자연키로 켜면 무시 목록에서 빠진다', () => {
    const s = toggleNaturalKeyColumn(base, 'created_at')
    expect(s.naturalKey).toEqual(['code', 'created_at'])
    expect(s.ignoredColumns).toEqual([])
  })

  it('자연키 컬럼을 무시로 켜면 자연키에서 빠진다', () => {
    const s = toggleIgnoredColumn(base, 'code')
    expect(s.ignoredColumns).toEqual(['created_at', 'code'])
    expect(s.naturalKey).toEqual([])
  })

  it('끄기는 상대 목록을 건드리지 않는다', () => {
    const s = toggleNaturalKeyColumn(base, 'code')
    expect(s.naturalKey).toEqual([])
    expect(s.ignoredColumns).toEqual(['created_at'])
  })

  it('켜는 순서가 키 구성 순서다', () => {
    const s = toggleNaturalKeyColumn(toggleNaturalKeyColumn({ ...base, naturalKey: [] }, 'org'), 'code')
    expect(s.naturalKey).toEqual(['org', 'code'])
  })
})

describe('CASE-studio-003 세트 완전성', () => {
  it('자연키가 없으면 no-natural-key', () => {
    expect(seedSetStatus({ naturalKey: [] })).toBe('no-natural-key')
  })
  it('있으면 ok', () => {
    expect(seedSetStatus({ naturalKey: ['code'] })).toBe('ok')
  })
})

describe('CASE-studio-004 세트 등록 후보', () => {
  const roles = table('roles', [col('c1', 'code')], ['c1'])
  const perms = table('permissions', [col('c2', 'code')], ['c2'])
  const v = table('v_summary', [col('c3', 'x')], [], { isView: true })

  it('뷰와 이미 세트가 있는 테이블을 제외한다', () => {
    const got = seedSetCandidates([roles, perms, v], [{ tableName: 'roles' }])
    expect(got.map((t) => t.name)).toEqual(['permissions'])
  })

  it('후보가 없으면 빈 목록', () => {
    expect(seedSetCandidates([roles], [{ tableName: 'roles' }])).toEqual([])
  })

  it('세트가 없으면 뷰만 빠진다(원래 순서 유지)', () => {
    expect(seedSetCandidates([roles, v, perms], []).map((t) => t.name)).toEqual(['roles', 'permissions'])
  })
})

describe('createSeedSet', () => {
  it('설계 소속·기본 자연키·안전한 관리 강도로 만든다', () => {
    const t = table('roles', [col('c1', 'code')], ['c1'])
    expect(createSeedSet(t)).toEqual({
      designId: 'd1',
      tableName: 'roles',
      naturalKey: ['code'],
      ignoredColumns: [],
      strength: 'ensure',
      rows: []
    })
  })
})
