import { Sparkles } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/shared/components/ui/button';
import { Select } from '@/shared/components/ui/select';
import { useDiagrams } from '@/features/virtual-diagram';
import { useAutoGenerateDocument } from '../model/useDocuments';

interface AutoDocGeneratorProps {
  onGenerated?: (content: string) => void;
}

export function AutoDocGenerator({ onGenerated }: AutoDocGeneratorProps) {
  const { data: diagrams } = useDiagrams();
  const autoGenerate = useAutoGenerateDocument();
  const [selectedDiagramId, setSelectedDiagramId] = useState('');

  function handleGenerate() {
    if (!selectedDiagramId) return;
    autoGenerate.mutate(selectedDiagramId, {
      onSuccess: (result) => {
        if (result.success) {
          onGenerated?.(result.data.content);
        }
      },
    });
  }

  return (
    <div className="flex items-center gap-2">
      <Select
        className="h-8 w-48 text-sm"
        value={selectedDiagramId}
        onChange={(e) => setSelectedDiagramId(e.target.value)}
      >
        <option value="">Select diagram...</option>
        {diagrams?.map((d) => (
          <option key={d.id} value={d.id}>{d.name}</option>
        ))}
      </Select>
      <Button
        variant="outline"
        size="sm"
        onClick={handleGenerate}
        disabled={!selectedDiagramId || autoGenerate.isPending}
      >
        <Sparkles className="size-4" />
        {autoGenerate.isPending ? 'Generating...' : 'Auto Generate'}
      </Button>
    </div>
  );
}
