import { getDb } from '#/infrastructure';
import type { IDocument } from '~/shared/types/db';

interface DocumentRow {
  id: string;
  name: string;
  content: string;
  auto_generated: number;
  created_at: string;
  updated_at: string;
}

function toDocument(row: DocumentRow): IDocument {
  return {
    id: row.id,
    name: row.name,
    content: row.content,
    autoGenerated: row.auto_generated === 1,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export const documentRepository = {
  list(): IDocument[] {
    const db = getDb();
    const rows = db.prepare('SELECT * FROM documents ORDER BY updated_at DESC').all() as DocumentRow[];
    return rows.map(toDocument);
  },

  getById(id: string): IDocument | null {
    const db = getDb();
    const row = db.prepare('SELECT * FROM documents WHERE id = ?').get(id) as DocumentRow | undefined;
    return row ? toDocument(row) : null;
  },

  create(data: {
    name: string;
    content: string;
    autoGenerated?: boolean;
  }): IDocument {
    const db = getDb();
    const id = crypto.randomUUID();
    db.prepare(
      'INSERT INTO documents (id, name, content, auto_generated) VALUES (?, ?, ?, ?)',
    ).run(id, data.name, data.content, data.autoGenerated ? 1 : 0);

    return this.getById(id)!;
  },

  update(
    id: string,
    data: { name?: string; content?: string },
  ): IDocument {
    const db = getDb();
    const sets: string[] = [];
    const values: unknown[] = [];

    if (data.name !== undefined) { sets.push('name = ?'); values.push(data.name); }
    if (data.content !== undefined) { sets.push('content = ?'); values.push(data.content); }

    if (sets.length > 0) {
      sets.push(`updated_at = datetime('now')`);
      values.push(id);
      db.prepare(`UPDATE documents SET ${sets.join(', ')} WHERE id = ?`).run(...values);
    }

    return this.getById(id)!;
  },

  deleteById(id: string): void {
    const db = getDb();
    db.prepare('DELETE FROM documents WHERE id = ?').run(id);
  },
};
